[package]
name = "mqtt-client"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc="*"
tokio="*"
bytes="*"
const_format = "*"
serde_json = "*"
chrono = "*"